# Generated by Django 5.2.8 on 2025-12-17 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminunit',
            name='region',
        ),
        migrations.DeleteModel(
            name='Point',
        ),
        migrations.DeleteModel(
            name='AdminUnit',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
