# Generated by Django 5.2.8 on 2025-12-17 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUnit',
            fields=[
                ('unit_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('TINH', 'Tỉnh'), ('XA', 'Xã'), ('HUYEN', 'Huyện')], default='TINH', max_length=20)),
                ('region_id', models.IntegerField(blank=True, null=True)),
                ('parent_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='submissions.adminunit')),
            ],
        ),
        migrations.CreateModel(
            name='RescueResource',
            fields=[
                ('resource_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('VEHICLE', 'Vehicle'), ('MEDICINE', 'Medicine'), ('FOOD', 'Food')], max_length=30)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('IN_USE', 'In use'), ('MAINTENANCE', 'Maintenance')], default='AVAILABLE', max_length=30)),
                ('capacity_total', models.IntegerField(default=0)),
                ('capacity_available', models.IntegerField(default=0)),
                ('location_lat', models.FloatField(blank=True, null=True)),
                ('location_lng', models.FloatField(blank=True, null=True)),
                ('admin_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='submissions.adminunit')),
            ],
        ),
        migrations.CreateModel(
            name='RescueTeam',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('BUSY', 'Busy'), ('INACTIVE', 'Inactive')], default='AVAILABLE', max_length=20)),
                ('contact_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('location_lat', models.FloatField(blank=True, null=True)),
                ('location_lng', models.FloatField(blank=True, null=True)),
                ('admin_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='submissions.adminunit')),
            ],
        ),
        migrations.CreateModel(
            name='SOSRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ASSIGNED', 'Assigned'), ('RESOLVED', 'Resolved'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=10)),
                ('address', models.TextField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('assistance_types', models.JSONField(blank=True, default=list)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sos_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RequestTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ASSIGNED', 'Assigned'), ('EN_ROUTE', 'En route'), ('ON_SCENE', 'On scene'), ('COMPLETED', 'Completed')], default='ASSIGNED', max_length=20)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_requests', to='submissions.rescueteam')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_teams', to='submissions.sosrequest')),
            ],
            options={
                'unique_together': {('request', 'team')},
            },
        ),
        migrations.CreateModel(
            name='RequestResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('DISPATCHED', 'Dispatched'), ('RETURNED', 'Returned')], default='REQUESTED', max_length=20)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_requests', to='submissions.rescueresource')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_resources', to='submissions.sosrequest')),
            ],
            options={
                'unique_together': {('request', 'resource')},
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('member_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('role_in_team', models.CharField(choices=[('LEADER', 'Leader'), ('MEDIC', 'Medic'), ('DRIVER', 'Driver'), ('SUPPORT', 'Support')], default='SUPPORT', max_length=20)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='submissions.rescueteam')),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'db_table': 'team_member',
                'indexes': [models.Index(fields=['team'], name='team_member_team_id_d51a09_idx'), models.Index(fields=['role_in_team'], name='team_member_role_in_56e93a_idx')],
            },
        ),
    ]
