# Generated by Django 5.2.8 on 2025-12-02 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RescueResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Hospital', 'Hospital'), ('Shelter', 'Shelter'), ('Supply', 'Supply'), ('Vehicle', 'Vehicle')], max_length=50)),
                ('capacity_total', models.IntegerField(default=0)),
                ('capacity_available', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Not Available', 'Not Available')], default='Available', max_length=50)),
                ('admin_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.adminunit')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.point')),
            ],
        ),
    ]
