# Generated by Django 5.2.8 on 2025-12-02 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='team_id',
        ),
        migrations.CreateModel(
            name='RescueTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Busy', 'Busy')], default='Available', max_length=50)),
                ('member_count', models.IntegerField(default=0)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('managed_by_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.adminunit')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='core.rescueteam'),
        ),
    ]
